version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

  cdn:
    image: nginx
    volumes:
      - ./cdn/images:/var/www/html/images
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5555:80

volumes:
  db:
