import type { NextPage } from "next";
import Head from "next/head";

import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>
          Get started by editing{" "}
          <code >pages/index.tsx</code>
        </p>

        <div>
          <Link href="/about">
            <a>
              <h2>About &rarr;</h2>
              <p>Learn About Us.</p>
            </a>
          </Link>

          <Link href="/assistance">
            <a >
              <h2>Assistance &rarr;</h2>
              <p>Need Assistance ?</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
