import type { NextPage } from "next";
import Head from "next/head";

import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/about">
            <a className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Learn About Us.</p>
            </a>
          </Link>

          <Link href="/assistance">
            <a className={styles.card}>
              <h2>Assistance &rarr;</h2>
              <p>Need Assistance ?</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
